version: "3.7"
services:
  app:
    build: .
    container_name: tech-challenge-group-57
    restart: always
    ports:
      - 8080:8080
    networks:
      - java-service-network
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/appdb?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - java-service-network
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: techchallenge
      MYSQL_PASSWORD: techchallenge
      MYSQL_ROOT_PASSWORD: techchallenge
networks:
  java-service-network: